dmotion:
    goalie:
        data:
             [30 ,  3000  , 3000,
              5  ,  -5.5 , 0,
              20   ,  15.5  , 20,
              10,  0   ,0,
              26 ,   0    , 0,
              170,   0    , 0,
              5,  0   , 0,
              15 ,  70   , 0,
              0,  26   , 24,
              24 ,  70   , 0,
              0  ,  0    ,  0
              ]
        row: 11
