dmotion:
    leftKick:
        data:
             [70   , 35    , 25, 60,
              0     , 0      ,  -0.5     , 0.0,    # cmx
              23.0  ,  23.0  ,  23.0   , 23.0,     # cmz
              6     , 6.8      ,  6.5      , 6.2,  # cm roll
              10     , 10      ,  -10      , 10,    # cm pitch
              -4.9  , -5.0   ,   -5.0  , -5.0,     # cm dy
              0     , -0     ,  -0     , 0,        # la x
              -0.5     , -3      ,    -1.0      , 1,        # la y
              1     , 2.8      ,  2.5      , 2.5,  # la z
              0     , 10     ,  10     , 10,       # la roll
              -2     , 12    ,  20    , -2,          # la pitch 
              -2    , -2     ,  -2     ,   -2,     # ra pitch 
              20    , 20     ,  20     , 20,
              0     , 0      ,  0      , 0, 
              20    , 20     ,  -40     , -40,
              0     , 0      , -50     ,-50,
              0, 0, 0.3, 0
              ]
        row: 17
        hip:  -52
        knee: -55
        ankle: -58
        ratio: 0.5
        debug: false
    rightKick:
        data:
            [80   ,   35  ,    25   ,  80,           # ticks
              0    ,  0    ,  -0.5        ,0.0,         # cm x
              23 , 23  ,   23     , 23,              # cm z
              -7 ,  -7,    -7,      -7,              # cm roll
              10    ,   10   ,  -8      ,    5,     # cm pitch
              4.8    ,   4.9 ,  4.9    , 4.9,        # cm dy
              0    ,  0   ,  0     ,  0,             # ra x
              0    ,  0    ,  4      ,  0,           # ra y
              0.2  ,   2.8 ,     2.6 ,    1.5,         # ra z
              0    ,   -10 ,  -10    ,  -10,         # ra r
              -2    ,   15   ,   15     ,   -2,      # ra p
              -2   ,  -2   ,  -2     ,  -2,          # la p
              0    ,  0    , 0       , 0,
              0    ,  0    ,  0      ,0,
              0    , 0     ,55       ,55,
              0    , 0     ,55      ,  55,
              0, 0,  0.35, 0
             ]
        row: 17
        hip:  -55
        knee: -55
        ankle: -55
        ratio: 0.5
        debug: false
