dmotion:
    motor:
      num : 18      
#         1     2     3     4     5     6     7     8     9     10   11     12    13    14    15    16    17    18    21   22
      id:   [   1 ,    2,   3,    4,   5,     6,    7,    8,    9,   10,   11,   12,   13,   14,   16,  18,  21,    22]
      init: [ 180,  157.5,  169.5,  178,  179,  183,  159,  180,  202.5,   202,  180,  179,  178, 200.5,  234,  142,  180,  180]
      zf:   [   1,   -1,   -1,   -1,   -1,    1,   -1,   -1,   1,   -1,   -1,    1,   -1,   -1,   -1,   1,   -1,    1]
      k:    [4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096,  4096, 4096, 4096, 4096]
      lb:   [   0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,     0,    0,    0,    0]
      ub:   [4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096, 4096,  4096, 4096, 1024, 4096]
      name:        ["right_arm_upper", "right_hip_pitch", "right_hip_roll", "right_hip_yaw", "right_knee", "right_ankle_pitch", "right_ankle_roll", "left_arm_upper", "left_hip_pitch", "left_hip_roll", "left_hip_yaw", "left_knee", "left_ankle_pitch", "left_ankle_roll", "left_arm_lower", "right_arm_lower", "head_pitch", "head_yaw"]
