dmotion:
    frontDown:
        data:
             [100, 100 ,  150  , 130,       # ticks
              0 , 14 ,  -6.5 , -8.5,         # cmx
              23.5 ,   7 ,  20  , 23,        # cmz
              15 ,  100,  70   , 20,         # cmp
              -2 ,     12 ,  -10    , -6,         # rap
              -2 ,  12 ,  -10    , -6,         # lap
              16,  16 ,  29.5   , 26,        # rhl
              110,  95 ,  110   , 60,         # rht
              16 ,    16 ,  29.5   , 26,
              110 , 95 ,  110   , 60
              ]
        row: 10

    backDown:
        data:
             [120   , 150   , 100   ,  100,          # ticks
              -12   , 10    , 10     ,  0,          # cmx
              16.5  , 11  , 15.5  ,  23,         # cmz
              -80   , -40   , -30     ,  10,          # cmp
              15    , 30    , 0     ,  -4,           # rap
              15    , 30    , 0     ,  -4,           # lap
              20    , 29.2    , 23    ,  26,
              -90  , -95  ,  0     ,  20,
              20    , 29.2    , 23    ,  26,
              -90  , -95  , 0     ,  20,
             ]
        row: 10
