dmotion:
    leftSideKick:
        data:
             [ 40 ,    30 ,    25    , 60 ,            # ticks
                0 ,     1  , 1      , 0     ,       # cmx
               22.0 ,   22.0  ,  22.0  , 22.0,         # cmz
                5.5 ,   6     , 6      , 6    ,        # cmr
              10     , 10      , -5    , 10,       # cmp
              -5.7  , -5.7   , -5.7,  -5.7 ,      # cm_dxy
              0     ,  -2     , 14 ,   0,       # rax
              0     , 0      , 0 ,      0 ,     # ray
              1     , 4.0    , 5.0 ,  3.0,       # raz
              10    , 10     , 10 ,   0,       # rar
              0     , -6      , -15 ,  -4,       # rap
              0,     25 ,   10, 0 ,              #ray
              -5    , -5     , -5  ,  -5 ,        # lap
              0    ,  0      , 0.8  ,   0        # delay
              ]
        row: 14
        roll: -8
        yaw: -15

    rightSideKick:
        data:
             [  40 ,    30 ,        200 ,    300 ,             # ticks
                 -2 ,    -2 ,       -2 ,      -2 ,           # cmx
              23.0 ,    23 ,    23.0 ,   23.0 ,          # cmz
               -10 ,    -13 ,    -14 ,   -14 ,      # cmr
                10 ,     10 ,       5 ,      5 ,         # cmp
               7.0 ,    7.5 ,     7.8 ,    7.8 ,         # cm_dxy
                 0 ,     9 ,      17 ,     14 ,           # rax
                 0 ,     -8 ,        8 ,      0 ,        # ray
                 0 ,     7 ,       7 ,      7 ,           # raz
                 0 ,    -10 ,    -10 ,    -10 ,           # ra_roll
                -4 ,     -10 ,      -6 ,     -6 ,          # ra_pitch
                 0 ,    -20,       0 ,      0 ,         # ra_yaw
                -4 ,     -4,      -4 ,     -4 ,           # la_pitch
                0,   0,           0.3 ,      0   
             ]
        row: 14
        roll: 5
        yaw: 5
