# PID 参数
PID_p_upper: &PID_p_upper 200.0
PID_p_lower: &PID_p_lower 900.0
PID_i: &PID_i 5.0
PID_d: &PID_d 0.0005

dancer_urdf_model:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
#1
  joint_body_head_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_head
    pid: {p: *PID_p_upper, i: *PID_i, d: *PID_d}
  joint_body_head2_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_head2
    pid: {p: *PID_p_upper, i: *PID_i, d: *PID_d}
  joint_arm_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_arm_left
    pid: {p: *PID_p_upper, i: *PID_i, d: *PID_d}
  joint_hand_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_hand_left
    pid: {p: *PID_p_upper, i: *PID_i, d: *PID_d}
  joint_arm_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_arm_right
    pid: {p: *PID_p_upper, i: *PID_i, d: *PID_d}
  joint_hand_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_hand_right
    pid: {p: *PID_p_upper, i: *PID_i, d: *PID_d}
#2s
  joint_body_hip_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_hip_left
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
  joint_body_hip2_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_hip2_left
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
  joint_leg_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg_left
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
  joint_leg2_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg2_left
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
  joint_leg3_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg3_left
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
  joint_leg4_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg4_left
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
#3
  joint_body_hip_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_hip_right
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
  joint_body_hip2_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_hip2_right
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
  joint_leg_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg_right
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
  joint_leg2_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg2_right
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
  joint_leg3_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg3_right
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
  joint_leg4_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg4_right
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
#4
  joint_body_hip_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_hip
    pid: {p: *PID_p_lower, i: *PID_i, d: *PID_d}
