dancer_urdf_model:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers ---------------------------------------
  joint_body_head_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_head
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_body_head2_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_head2
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_arm_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_arm_left
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_hand_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_hand_left
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_arm_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_arm_right
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_hand_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_hand_right
    pid: {p: 10.0, i: 0.01, d: 0}

  joint_body_hip_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_hip_left
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_body_hip2_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_hip2_left
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_leg_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg_left
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_leg2_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg2_left
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_leg3_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg3_left
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_leg4_left_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg4_left
    pid: {p: 10.0, i: 0.01, d: 0}

  joint_body_hip_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_hip_right
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_body_hip2_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_body_hip2_right
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_leg_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg_right
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_leg2_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg2_right
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_leg3_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg3_right
    pid: {p: 10.0, i: 0.01, d: 0}
  joint_leg4_right_controller:
    type: effort_controllers/JointPositionController
    joint: joint_leg4_right
    pid: {p: 10.0, i: 0.01, d: 0}
